### ISSUE TITLE
@Input() modules

### ISSUE THREAD

**Issue by ndl7** [changhuixu/ngx-quill-lite#10]
Hi,

Appreciate your work.

Is there any way you could add Input() modules, so then it would be possible to bind the toolbar config?

`[modules]="quillModuleConfig"`

```
public quillModuleConfig = {
    toolbar: [
        ['bold', 'italic', 'underline'],
        [{ 'header': 1 }, { 'header': 2 }],
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
        [{ 'color': [] }, { 'background': [] }],
        [{ 'align': [] }],
        ['clean']
    ]
};
```

Thank you.

**Comment by changhuixu** [comment]
Hi @ndl7 , I added common toolbar elements as custom HTML. If the component needs to bind toolbar options, then I will need to use Quill's default toolbar. It's a trade-off. I wish there's an easy way.
If you have some ideas, please go ahead submit a pull request. Thank you.
