### ISSUE TITLE
Looking for github codes for the lazy loading article

### ISSUE THREAD

**Issue by bemivcf** [changhuixu/ngx-quill-lite#5]
Hi, I came across your article @ https://codeburst.io/lazy-loading-external-javascript-libraries-in-angular-3d86ada54ec7  and was interested to check out your complete codes used inside the component. I didn't see anything that was familiar to what mentioned in the article. Please help.

**Comment by changhuixu** [comment]
Hi, @bemivcf 

Please take a look at below 2 files:
https://github.com/changhuixu/ngx-quill-lite/blob/master/projects/ngx-quill-lite/src/lib/quill-editor.service.ts
https://github.com/changhuixu/ngx-quill-lite/blob/master/projects/ngx-quill-lite/src/lib/quill-editor/quill-editor.component.ts

Thanks.

**Comment by bemivcf** [comment]
Thank you!

**Comment by bemivcf** [comment]
Could you please explain a little bit about declare var [name] : any; and how I should use it? I tried to use the technique in the article with a different third library and it didn't work.  Included the link below to my current attempt for reference. Appreciate any input.

[stackblitz link to code](https://stackblitz.com/edit/pr-lazy-loading)

**Comment by changhuixu** [comment]
![image](https://user-images.githubusercontent.com/16184464/60335349-5cd84480-9963-11e9-9dfa-986a245bc75d.png)

**Comment by bemivcf** [comment]
Ha, that is a cool approach, thanks
